### ISSUE TITLE
Test `$apply` implementation

### ISSUE THREAD

**Issue by dubdabasoduba** [google/android-fhir#2143]
**Task Description**

- ONA plans to use `$apply` on a project and would like to review its readiness by accomplishing the following tasks:

**Implementation Plan**

- [ ]  Test `$apply` using the examples provided by the SDK.
- [ ]  Test `$apply` using the Measles content available on the [[Smart Immunizations IG](https://github.com/WorldHealthOrganization/smart-immunizations/blob/cleanup/input/resources/plandefinition/IMMZ.DT.08.Measles.json)](https://github.com/WorldHealthOrganization/smart-immunizations/blob/cleanup/input/resources/plandefinition/IMMZ.DT.08.Measles.json).
- [ ]  Write documentation that highlights the following items:
    - [ ]  Does `$apply` work with the example content in the SDK?
        - If not, where does it fail?
    - [ ]  Does `$apply` work with the content in the IG?
        - If not, where does it fail? What is the difference between the resources in the IG and the ones in the SDK examples?
        - [ ]  Does `$apply` generate the expected resources from the IG content? The expected resources are:
            - [ ]  CarePlan
            - [ ]  ImmunizationRecommendation

**Comment by dubdabasoduba** [comment]
@f-odhiambo @jingtang10 @pld @fredhersch @litlfred

**Comment by dubdabasoduba** [comment]
Next steps are to test the `$apply` with PlanDefs [here](https://github.com/google/fhir-app-examples/tree/main/configurablecare)
