### ISSUE TITLE
[Roadmap] sdc-alpha-03 release | ERD 12-06-30

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#254]
This alpha-03 release of the data-capture library will add in the additional features:

- [x] Pagination #186 
- [x] Language support #465 
- [x] Validation API #374 
- [x] Element extension (regex) #466 
- [x] Element extension (min/max Length) #185 
- [x] Handle required fields in questionnaires https://github.com/google/android-fhir/issues/470
- [x] Auto complete https://github.com/google/android-fhir/issues/520
