### ISSUE TITLE
Search requirements 

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#484]
**Describe the issue to be researched**
Search requirements for the SDK to support

**Describe the goal of the research**

1. Capture all of the common search use cases that the FHIR SDK needs to support for implementers to develop solutions
2. Gap analysis of existing search features (completed or on roadmap). Update roadmap accordingly
3. Identify edge cases and prioritise these on the roadmap

**Describe the methodology**
- Document current set of search use cases
- Reach out to implementers through various forums and surface the common use cases
- Map those use cases to technical requirements - either existing or new

**Would you like to work on the issue?**
Yes

**Comment by fredhersch** [comment]
Current set of use cases surfaced have been [documented here](https://docs.google.com/document/d/1p4otLZQBye8EYaqG5TnKL1NVA-7Hf-OX-ewd4ypAEUM/edit?ts=60a4bc57)

@pld @f-odhiambo @kunjan8794 PTAL

**Comment by fredhersch** [comment]
If there are additional use cases that have not been covered. Please add to this thread. Thanks

**Comment by f-odhiambo** [comment]
**Search** 

- [ ] 1. Patient Name - First name, Last name 
- [ ] 2. Family name? ANC Family registration and retrieve  - Head of the household?
- [ ] 3. Identifier - Covax Smart Vaccine Certificate retrieved by Barcode ID
- [ ] 4. Search by multiple resource types #611 i.e. Encounter, Observations, Practitioners, Related person  - Next of kin / Mom and tagged to a given patient or contact details 
- [ ] 5. Location  (show me all patients who require ANC visits, )- Support location search #475
- [ ] 6. Allow implementers to specify custom search fields #637


**Filter** 
- [ ] 1.  Due tasks/ Services
- [ ] 2. Overdue tasks/ Services
- [ ] 2. User can sort by geographic location 
- [ ] 3. Service per location - Immunization

**Comment by fredhersch** [comment]
Thanks Francis. 

- For each can you provide a crisp example of the search you want to perform. 
- Specifically for Head of Household, this is dependent on how you are modelling this
- For the identifier, how is this being stored
- Multiple resource types in being worked on at the moment. Please share a specific example of a query
- Location is not being worked on currently. Does someone at Ona want to pick this up? 
- Custom search fields looks like the requirement is not clear yet. Let's discuss

**Comment by f-odhiambo** [comment]
@fredhersch I will work on some sample use cases/examples and hare in the course of this week
