### ISSUE TITLE
[Roadmap] fhirengine-alpha-02 release: ERD 04-06-21

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#508]
This alpha-02 release of the fhirengine library addresses a dependency issue that was causing an error when trying to build from maven and API change related to Sync.

- [x] Remove CQL dependency in fhirengine: https://github.com/google/android-fhir/pull/454
- [x] Rework sync API to be separate form data access API: https://github.com/google/android-fhir/pull/482

Release checklist:
- [x] Have run relevant tests
- [x] Documentation updated (if required)
- [x] Released
