### ISSUE TITLE
[Roadmap] fhirengine-alpha-03 | ERD 30-06-21

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#509]
FHIR engine alpha 03 release. Adds additional features across search, sync and data-access:

Search:
- [x] modifiers with :contains #426 
- [x] modifiers with :exact #426
- [x] multiple search criteria joined by AND operator  
- [x] search by number type #435 
- [x] search by token type #461 
- [x] search by date #375 

Sync:
- [x] Retry functionality https://github.com/google/android-fhir/issues/535

Data access:
- [x] Database failure model design and implementation: #510

**Comment by Tarun-Bhardwaj** [comment]
It would be good to have milestones listed for each epic, just like we have one for this particular Epic. If we also list milestones for each issue in the epic, it would help us determine the weakest link (critical path) in the set of issues that are listed under the epic.
