### ISSUE TITLE
[Roadmap] Documentation with code snippets | ERD 15-09-21

### ISSUE THREAD

**Issue by fredhersch** [google/android-fhir#564]
Update current documentation in preparation for the up-coming beta-release in Q4. Areas to work on include:

- [ ] General instructions on how to use the SDK
- [ ] Addition of code snippets and reference examples
- [ ] Documentation of common use cases and patterns for implementers

**Comment by omarismail94** [comment]
Closing this as it's obsolete
